Class {
	#name : #ObjectBrowserLoopLessonTestCase,
	#superclass : #TestCase,
	#category : #'ObjectBrowser-Tests'
}

{ #category : #'as yet unclassified' }
ObjectBrowserLoopLessonTestCase >> testFileInEmptyLessonSuccess [

]

{ #category : #'as yet unclassified' }
ObjectBrowserLoopLessonTestCase >> testFileInLessonWithObjectsNoStateSuccess [
]

{ #category : #'as yet unclassified' }
ObjectBrowserLoopLessonTestCase >> testFileInLessonWithObjectsStateSuccess [
]

{ #category : #'as yet unclassified' }
ObjectBrowserLoopLessonTestCase >> testFileOutEmptyLessonSuccess [

]

{ #category : #'as yet unclassified' }
ObjectBrowserLoopLessonTestCase >> testFileOutLessonWithObjectsNoStateSuccess [
]

{ #category : #'as yet unclassified' }
ObjectBrowserLoopLessonTestCase >> testFileOutLessonWithObjectsStateSuccess [
]
